### ISSUE TITLE
dict.cc plugin malfunctioning

### ISSUE THREAD

**Issue by Artox** [tuxor1337/dictmaster#3]
So I found 2 problems with the dictcc plugin:
1) dictcc.py:6 typo dictmaster.utils should be dictmaster.util

2) I got trouble converting the DE-EN dictionary
That error message is purely beyond my python knowledge ... but it seems it has trouble with some special characters (e.g. ö,ä).

./dictmaster.py dictcc --popts ../../cbfdomogdm-125253101196-eu8ae6.zip 
Running plugin 'dictcc'.
Output will be written to 'data/dictcc/'.
Unzipping... done.                       
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/josua/tmp/dictmaster/dictmaster/postprocessor.py", line 47, in run
    self.process()
  File "/home/josua/tmp/dictmaster/dictmaster/postprocessor.py", line 101, in process
    self.do_line(line)
  File "/home/josua/tmp/dictmaster/dictmaster/postprocessor.py", line 122, in do_line
    subfields[0][i] = subfields[0][i].strip()
TypeError: 'unicode' object does not support item assignment

 done.
filename=data/dictcc/stardict.ifo
 done.

Plugin 'dictcc' quit.

**Comment by tuxor1337** [comment]
I hate to say that, but the dict.cc-Plugin was just a proof of concept. I never really tested it ;) And the output stardict might be really much less convenient than the original dict.cc interface.

But now about your issues: Of course you are right regarding the first point. The second part is similarly trivial. The fix is on the way...

**Comment by Artox** [comment]
Thanks for your great work, seems to work fine now.
